/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package procliente;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.print.attribute.standard.MediaSize.Other;

import java.io.*;
import java.net.*;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.print.attribute.standard.MediaSize.Other;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author karenandreabarretorasquin
 */
public final class CrearArchivo extends javax.swing.JFrame {

    String carpetausuario;
    /**
     * Creates new form GestionArchivos
     */
    GestionArchivos padre;

    public CrearArchivo() {

        initComponents();
        //conexion();


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Usuario2 = new javax.swing.JLabel();
        crear = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Usuario = new javax.swing.JLabel();
        Usuario1 = new javax.swing.JLabel();
        Usuario3 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        contenido = new javax.swing.JTextArea();
        username = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel1.setText("Biblioteca de Archivos");

        Usuario2.setFont(new java.awt.Font("Lucida Grande", 2, 14)); // NOI18N
        Usuario2.setText("Usuario:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        crear.setText("Crear Archivo");
        crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearActionPerformed(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.setActionCommand("");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel2.setText("Crear Archivo");

        Usuario.setFont(new java.awt.Font("Lucida Grande", 2, 14)); // NOI18N
        Usuario.setText("Nombre:");

        Usuario1.setFont(new java.awt.Font("Lucida Grande", 2, 14)); // NOI18N
        Usuario1.setText("Usuario:");

        Usuario3.setFont(new java.awt.Font("Lucida Grande", 2, 14)); // NOI18N
        Usuario3.setText("Contenido:");

        contenido.setColumns(20);
        contenido.setRows(5);
        jScrollPane1.setViewportView(contenido);

        username.setFont(new java.awt.Font("Lucida Grande", 2, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel3.setText("Dropbox Ucab");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(Usuario3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 86, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(Usuario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 68, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jScrollPane1)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, nombre, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 244, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(112, 112, 112))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(cancelar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 147, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(54, 54, 54)
                        .add(crear, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 147, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(103, 103, 103))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jLabel3)
                            .add(jLabel2))
                        .add(198, 198, 198))))
            .add(layout.createSequentialGroup()
                .add(153, 153, 153)
                .add(Usuario1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 68, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(username, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 151, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, Usuario1)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, username, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jLabel3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel2)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(nombre, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(Usuario))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(Usuario3))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cancelar)
                    .add(crear))
                .add(30, 30, 30))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-513)/2, (screenSize.height-328)/2, 513, 328);
    }// </editor-fold>//GEN-END:initComponents

    private void crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearActionPerformed
        // TODO add your handling code here:

        try {
            File archivo = new File(this.carpetausuario + "/" + this.nombre.getText());
            FileWriter fw = new FileWriter(archivo);
            BufferedWriter bw = new BufferedWriter(fw);
            PrintWriter salida = new PrintWriter(bw);
            salida.println(this.contenido.getText());
            salida.close();
            JOptionPane.showMessageDialog(null, "Archivo Creado Correctamente", "CONFIRMACION", JOptionPane.OK_OPTION);

            padre.agregarfila(this.nombre.getText(), "10KB", "16-11-2012", "16-11-2012");
            XMLCliente xml = new XMLCliente();
            xml.escribirArchivos(this.nombre.getText(), "10KB", "16-11-2012", "16-11-2012", this.carpetausuario);

              XMLnodos xmlnodo = new XMLnodos();

            for (int i = 0; i < xmlnodo.cantNodos(); i++) {
             
                xmlnodo.cargaArchivos(i);
                HiloReplicador hiloReplicador;
                // OJO EL 1200 ES EL PUERTO DE ENVIAR, EL DE ESCUCHA SE ESTA USANDO POR ARGUMENTO
                hiloReplicador = new HiloReplicador(Datos.getIp_vecino(), Datos.getPuerto_entrada(), Datos.getPuerto_salida(), archivo, this.carpetausuario);
                hiloReplicador.start();


            }









        } catch (java.io.IOException ioex) {
            System.out.println("se presento el error: " + ioex.toString());
            JOptionPane.showMessageDialog(null, "Archivo NO creado", "ERROR", JOptionPane.ERROR_MESSAGE);
        }


        padre.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_crearActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Operacion no realizad", "Cancelar", JOptionPane.CLOSED_OPTION);
        GestionArchivos gestor = new GestionArchivos();
        gestor.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelarActionPerformed

    public GestionArchivos getPadre() {
        return padre;
    }

    public void setPadre(GestionArchivos padre) {
        this.padre = padre;
    }

    public JLabel getUsername() {
        return username;
    }

    public void setUsername(JLabel username) {
        this.username = username;
    }

    public String getCarpetausuario() {
        return carpetausuario;
    }

    public void setCarpetausuario(String carpetausuario) {
        this.carpetausuario = carpetausuario;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Usuario;
    private javax.swing.JLabel Usuario1;
    private javax.swing.JLabel Usuario2;
    private javax.swing.JLabel Usuario3;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextArea contenido;
    private javax.swing.JButton crear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombre;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
